# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Manuel Frias
title: Estudiante de la Tecnicatura Universitaria en Programación
email: frias.manuel@hotmail.com 
website: www.github.com/FriasManuel

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics#
github_username:  FriasManuel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: m__fs_
linkedin_username: manuel-frias
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Soy una persona que se adapta rápido a diferentes formatos de trabajo. 
  Me considero respetuoso, compañero, y perseverante. 
  Trato de seguir aprendiendo siempre y como parte de ese objetivo me encuentro cursando la Tecnicatura Universitaria en Programación, 
  en la Universidad Nacional de Hurlingham. 
  
  Esforzarme, aprender, crecer, dar lo mejor de mí, es lo que me mantiene en la búsqueda constante de nuevos desafíos. 
  Como parte de esa búsqueda y esa madurez que te da una vida laboral activa, es que valoro el ámbito de trabajo donde puedo sumar conocimientos y aplicarlos. 
  Busco desarrollarme en un ambiente dinámico y fluido, donde pueda crecer y seguir adquiriendo experiencia.
content:
  - title: Hoy # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Carpinteria M.V.
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

#-----------------------EXPERIENCIA LABORAL----------------------------------------------------
  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Energia Global SRL
        link: www.energiaglobal.com.ar
        # link_text: boringcompany.com
        sub_title: Administración Producción
        caption: Marzo 2018 - Diciembre 2020
        quote: >
          Por mi desempeño, obtengo un asenso e ingreso a la Oficina Técnica. Mis tareas eran la coordinacion entre departamentos y la asistencia en la produccion.
        description: | # this will include new lines to allow paragraphs
          - Administración de Producción.
          - Coordinación entre los departamentos de Producción, Ventas, Compras y Logística.
          - Ingreso y egreso de mercadería.
          - Control de stock.
          - Compras.
          - Desarrollo eléctrico de toda la línea de producción.
          - Digitalización de cada desarrollo.
          - Integrante de un grupo de empleados encargados de la reestructuración de los procesos productivos de la empresa.

#-----------------------EXPERIENCIA LABORAL #1----------------------------------------------------
      - layout: left
        title: Energia Global SRL
        link: www.energiaglobal.com.ar
        # link_text: boringcompany.com
        sub_title: Administración Producción
        caption: Junio 2015 - Diciembre 2018
        quote: >
          Ingrese a la empresa como Operario, me encargaba del desarrollo de tableros para la automatización de Grupos Electrógenos.
        description: | # this will include new lines to allow paragraphs
          - Montaje y cableado de tableros eléctricos.
          - Montaje en obra.
          - Digitalización de cada desarrollo.

#-----------------------EXPERIENCIA LABORAL #2----------------------------------------------------
      - layout: left
        title: GP ARGENTINA
        sub_title: Desarrollador Eléctrico
        caption: Diciembre 2012 - Junio 2015
        quote: >
          Ingrese a la empresa como Operario, me encargaba del desarrollo de tableros para la automatización de Bombas de agua.
        description: | # this will include new lines to allow paragraphs
          - Desarrollo de tableros para la automatización de bombas de agua. 
          - Montaje y cableado de tableros eléctricos. 
          - Montaje en obra. 

#-----------------------EXPERIENCIA LABORAL #3----------------------------------------------------
      - layout: left
        title: INGENIERIA & SERVICIOS
        sub_title: Dibujante de AutoCAD (Freelance)
        caption: Septiembre 2014 - Noviembre 2014
        quote: >
          Dibujante de AutoCad Freelance para empresa de Ingeniería Eléctrica
        description: | # this will include new lines to allow paragraphs
          Barrio Cerrado "EL CANTON". Proyecto Instalación eléctrica C.P.D. (Centro de Procesamiento de Datos) e implantación grupo electrógeno.

          Planos: 
          Layout Iluminación.
          Layout Tomacorrientes.
          Layout M.B.T. (Muy Baja Tensión)
          Layout P.A.T. (Puesta a Tierra de protección, y Protección de Descargas Atmosféricas)
          Layout Canalizaciones Troncales.
          Layout Canalizaciones Seccionales.
  
#-----------------------EXPERIENCIA LABORAL #4----------------------------------------------------
      - layout: left
        title: INGENIERIA & SERVICIOS
        sub_title: Dibujante de AutoCAD (Freelance)
        caption: Junio 2013 - Agosto 2013
        quote: >
          Dibujante de AutoCad Freelance para empresa de Ingeniería Eléctrica
        description: | # this will include new lines to allow paragraphs
          UNILEVER ARGENTINA. Proyecto Instalación eléctrica de Depósito de etiquetas, Laboratorio de Físico-Química y Laboratorio de Calidad - Planta Tortuguitas.

          Planos: 
          Layout Iluminación.
          Layout Tomacorrientes.
          Layout M.B.T. (Muy Baja Tensión)
          Layout P.A.T. (Puesta a Tierra de protección, y Protección de Descargas Atmosféricas)
          Layout Canalizaciones Troncales.
          Layout Canalizaciones Seccionales.

#-----------------------EXPERIENCIA LABORAL #5----------------------------------------------------
      - layout: left
        title: Estudio Rodriguez - Servicios Aduaneros
        sub_title: Empleado administrativo
        caption: Octubre 2008 - Diciembre 2012
        quote: >
          Me encargaba da le gestion de documentación.
        description: | # this will include new lines to allow paragraphs
          - Emisión de documentos para ser presentados ante el SENASA.
          - Confección y gestión de Avisos de llegada de Importación.
          - Gestión de Autorizaciones de Importación de productos.
          - Confección y gestión de formularios en Senasa Vegetal (Avisos de Importación, Madera, Afidi).
          - Inscripción y reinscripción como Importador/Exportador.
          - Confección y gestión de Certificados Sanitarios definitivos de Exportación.
          - Secretaría de Industria y Comercio.
          - Confección y gestión de Certificados de Origen según el Sistema Generalizado de Preferencias.
          - Confección y gestión de Certificados de Origen de productos y mercadería a exportar.
          - C.A.E. (Cámara Argentina de Exportadores)
          - A.I.E.R.A (Asociación de Importadores y Exportadores de la República Argentina)
          - C.E.R.A (Cámara de Exportadores de la República Argentina)

#-----------------------EXPERIENCIA LABORAL #5----------------------------------------------------
      - layout: left
        title: Estudio Rodriguez - Servicios Aduaneros
        sub_title: Cadete
        caption: Junio 2005 - Octubre 2008
        quote: >
          Realizaba la gestion de la documentacion aduanera, la entrega de formularios y tramitacion varia de despacho.
        description: | # this will include new lines to allow paragraphs
          Trámites:
          - SENASA.
          - Senasa Vegetal (Avisos de Importación, Madera, Afidi).
          - Secretaría de Industria y Comercio.
          - C.A.E. (Cámara Argentina de Exportadores)
          - A.I.E.R.A (Asociación de Importadores y Exportadores de la República Argentina)
          - C.E.R.A (Cámara de Exportadores de la República Argentina)
          - Agencias Marítimas.
          - Terminales Portuarias: Pagos de ingreso y egreso de contenedores.

#-----------------------EXPERIENCIA LABORAL #6----------------------------------------------------
      - layout: left
        title: IIPESA
        sub_title: Ayudante de Electricista
        caption: Enero 2004 - Marzo 2005
        quote: >
          Ingrese a la empresa como operario. Al mismo tiempo realizaba el desarrollo digital de los tableros electricos en AutoCad
        description: | # this will include new lines to allow paragraphs
          - Montaje, cableado y ensamblado de tableros Eléctricos.
          - Automatización Industrial.
          - Instalación en fábrica.

#-----------------------EXPERIENCIA LABORAL #1----------------------------------------------------  
      - layout: left
        title: INGENIERIA & SERVICIOS
        sub_title: Ayudante de Electricista
        caption: Abril 2002 - Diciembre 2003
        quote: >
          La empreza pertenecia a mi padre. Mientras cursaba el ultimo año del secundario, participaba activamente del desarrollo de la empresa.
        description: | # this will include new lines to allow paragraphs
          - Dibujos de planos electromecánicos, Arquitectura, Ingeniería Eléctrica. 
          - Montaje y cableado de tableros Eléctricos.

#-----------------------EDUCACION----------------------------------------------------
  - title: Educación # Title for the section
    layout: list # Type of content section (list/text)
    content:
#-------------------Tecnicatura Univeritaria en Programación------------------------      
      - layout: left
        title: Universidad Nacional de Hurlingham - UNaHur
        caption: 2021 - Actualidad
        link: www.unahur.edu.ar
        sub_title: Tecnicatura Universitaria en Programación
        quote: >
          La Universidad Nacional de Hurlingham es una institucion de altos estudios creada en 2014 en el Oeste del gran Bs As. Abre sus puertas en 2016 con un amplia oferta academica.
        description: | # this will include new lines to allow paragraphs
          Materias Aprobadas: 07/23
            - Introducción a lógica y problemas computacionales
            - Organización de computadoras I
            - Matemática I
            - Nuevos entornos y lenguajes: la producción de conocimiento en la cultura digital
            - Ingles II
            - Ingles I
            - Robótica

          Materias en curso (Segundo cuatrimestre / 2022)
            - Matematica II
            - Programacion Estructurada
            - Taller de lengajes de marcado y tecnologias web.

          Promedio Actual: 8,86
#-------------------Ingenieria Electrica------------------------      
      - layout: left
        title: Universidad Nacional de Hurlingham - UNaHur
        caption: 2016 - Actualidad
        link: www.unahur.edu.ar
        sub_title: Ingeniería Eléctrica
        quote: >
          La Universidad Nacional de Hurlingham es una institucion de altos estudios creada en 2014 en el Oeste del gran Bs As. Abre sus puertas en 2016 con un amplia oferta academica.
        description: | # this will include new lines to allow paragraphs
          Materias Aprobadas: 22/44
            - Ingeniería ambiental, seguridad e higiene
            - Mediciones eléctricas
            - Economía
            - Electrónica
            - Materiales eléctricos
            - Programación
            - Electrotecnia
            - Estabilidad y resistencia de los materiales
            - Algebra y Geometría Analítica
            - Física I
            - Probabilidad y estadística
            - Organización Industrial
            - Análisis Matemático I
            - Sistemas de representación gráfica
            - Nuevos entornos y lenguajes: la producción de conocimiento en la cultura digital
            - Ingles II
            - Ingles I
            - Robótica
            - Introducción a la Energía Eléctrica II
            - Introducción a la Energía Eléctrica I
            - Introducción al análisis matemático
            - Química General

          Promedio Actual: 8,67

#-------------------Udemy------------------------      
      - layout: left
        title: UDEMY
        caption: 2022
        link: www.udemy.com
        additional_links: udemy-certificate.s3.amazonaws.com/pdf/UC-cb1affa2-30b0-4e95-8ad7-fd42425ec58e.pdf
        sub_title: Aprende a programar desde las bases | Programación
        quote: >
          Curso práctico de programación en C. 
        description: | # this will include new lines to allow paragraphs
           Bases y fundamentos de la programación para el puedas desempeñar en el mundo del desarrollo de software. 
           Conceptos básicos y practica programando directamente el el lenguaje C.
           
           

#-------------------Curso de AutoCad------------------------      
      - layout: left
        title: Universidad Nacional de Tres de Febrero - UNTREF
        caption: 2010 
        link: www.untref.edu.ar
        sub_title: Curso de AutoCad I
        quote: >
          Universidad Nacional de Tres de Febrero. Curso y taller de AutoCad
        description: | # this will include new lines to allow paragraphs
          Curso de AutoCad en la Universidad Nacional de Tres de Febrero, en 2010 a cargo del Arquitecto Leonardo Magliolo.

    
#---------------------------------------------
  - title: Algo mas sobre mí
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
      Look at this cool image  
      [Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag